image: Visual Studio 2017

before_build:
  - nuget restore Dabble.sln

configuration:
  - Debug
  - Release

build:
  project: Dabble.sln

after_build:
  - ps: cd test/UnitTests
  - ps: dotnet test --no-build --configuration $env:CONFIGURATION --verbosity normal

test: off
